Perfect! We’ll go with **Option A — full category text prefix** and include **fun, interesting, and historical facts** across all 8 categories.

Because this is **very long (1000 facts)**, I’ll generate it in **a single `facts.js` file ready to paste**. I’ll organize it **125 facts per category**, with each fact prefixed by its category.

Here’s the **complete `facts.js` for your app (Version 1.3)**:

```javascript
const facts = [
/* 1. First Impressions Guide — 125 facts */
"First Impressions Guide: Guatemalans are known for warm hospitality.",
"First Impressions Guide: People often greet with a handshake and a smile.",
"First Impressions Guide: Dressing neatly is appreciated in public spaces.",
"First Impressions Guide: Arriving on time is a sign of respect.",
"First Impressions Guide: Friendly small talk is common before formal conversations.",
"First Impressions Guide: A modest compliment about local traditions is appreciated.",
"First Impressions Guide: Casual social events may start slightly late.",
"First Impressions Guide: It’s common to exchange pleasantries before business.",
"First Impressions Guide: Eye contact is considered respectful.",
"First Impressions Guide: Smiling and friendly gestures go a long way.",
"First Impressions Guide: First names may be used after introduction.",
"First Impressions Guide: Titles + last names show respect in formal settings.",
"First Impressions Guide: Guatemalans value friendliness and politeness.",
"First Impressions Guide: A small gift is appreciated when visiting a home.",
"First Impressions Guide: Bringing flowers is a nice gesture when invited.",
"First Impressions Guide: Be prepared for warm and curious questions.",
"First Impressions Guide: Humor and light jokes are welcomed after rapport.",
"First Impressions Guide: Always say thank you graciously.",
"First Impressions Guide: Showing interest in Mayan culture impresses locals.",
"First Impressions Guide: Guatemalans speak Spanish with regional accents.",
"First Impressions Guide: Simple greetings in Spanish are appreciated.",
"First Impressions Guide: Basic Maya greetings also show respect.",
"First Impressions Guide: It’s common to be called by full name first.",
"First Impressions Guide: Being polite trumps being fast or rushed.",
"First Impressions Guide: Casual clothing is fine outside formal meetings.",
"First Impressions Guide: Bright, cheerful attire fits cultural norms.",
"First Impressions Guide: Avoid overly flashy jewelry on first meeting.",
"First Impressions Guide: A respectful tone wins respect back.",
"First Impressions Guide: Guatemalans enjoy telling stories about home.",
"First Impressions Guide: Listening carefully matters.",
"First Impressions Guide: Avoid interrupting people while speaking.",
"First Impressions Guide: Speak clearly, not loudly.",
"First Impressions Guide: Showing patience is appreciated.",
"First Impressions Guide: Nods and smiles show engagement.",
"First Impressions Guide: Curiosity about languages is respected.",
"First Impressions Guide: A good first impression starts with kindness.",
"First Impressions Guide: Clean, tidy shoes make a good impression.",
"First Impressions Guide: Being courteous to elders is important.",
"First Impressions Guide: Guatemalans show respect with gentle manners.",
"First Impressions Guide: Avoid discussing politics or sensitive history unless asked.",
"First Impressions Guide: Talk about weather or travel initially.",
"First Impressions Guide: A friendly hello opens doors quickly.",
"First Impressions Guide: Learn a few local phrases before arrival.",
"First Impressions Guide: Small compliments about food help break ice.",
"First Impressions Guide: People may ask about your hometown.",
"First Impressions Guide: Ask polite questions about theirs too.",
"First Impressions Guide: Accept invitations graciously.",
"First Impressions Guide: Say goodbye warmly when departing.",
"First Impressions Guide: Leaving with a smile leaves good memories.",
"First Impressions Guide: Offer a thank you card after visits.",
"First Impressions Guide: Be genuine; insincerity is noticed.",
"First Impressions Guide: Respect customs to show cultural awareness.",
"First Impressions Guide: Show willingness to learn.",
"First Impressions Guide: Patience and courtesy open doors.",
"First Impressions Guide: Positive energy is universally welcomed.",
"First Impressions Guide: Try local greetings before formal ones.",
"First Impressions Guide: Be calm even if nervous.",
"First Impressions Guide: Avoid slang in early conversations.",
"First Impressions Guide: Use polite language consistently.",
"First Impressions Guide: Say “por favor” and “gracias” often.",
"First Impressions Guide: Enthusiasm shows respect for the experience.",
"First Impressions Guide: Speak slowly to ensure understanding.",
"First Impressions Guide: Ask how they prefer to be addressed.",
"First Impressions Guide: Learn basic courtesy phrases.",
"First Impressions Guide: Respect cultural differences openly.",
"First Impressions Guide: Observing others helps guide behavior.",
"First Impressions Guide: Watch and mirror local etiquette.",
"First Impressions Guide: Respect personal space when appropriate.",
"First Impressions Guide: Accept differences with a smile.",
"First Impressions Guide: Treat everyone with equal respect.",
"First Impressions Guide: Respond politely to questions.",
"First Impressions Guide: Be gracious in receiving compliments.",
"First Impressions Guide: Laugh politely at appropriate moments.",
"First Impressions Guide: Speak authentically, not theatrically.",
"First Impressions Guide: Avoid dominating conversations.",
"First Impressions Guide: Look for friendly cues.",
"First Impressions Guide: Always keep a polite demeanor.",
"First Impressions Guide: Cultivate inner calm in interactions.",
"First Impressions Guide: Make introductions clear and friendly.",
"First Impressions Guide: Use simple phrases before complex ones.",
"First Impressions Guide: Be ready to adapt gracefully.",
"First Impressions Guide: People appreciate humility.",
"First Impressions Guide: Avoid dismissive gestures.",
"First Impressions Guide: Honor local traditions verbally.",
"First Impressions Guide: A warm goodbye seals a good visit.",
"First Impressions Guide: Leave contact information amicably.",
"First Impressions Guide: Respect time commitments given.",
"First Impressions Guide: Thank everyone before leaving.",
"First Impressions Guide: Be mindful of tone and gestures.",
"First Impressions Guide: Express appreciation for hospitality.",
"First Impressions Guide: Recognize local effort to help you.",
"First Impressions Guide: Be courteous, always.",
"First Impressions Guide: Be genuinely interested, not just polite.",
"First Impressions Guide: Smile to show friendliness.",
"First Impressions Guide: A sincere thank‑you never hurts.",
"First Impressions Guide: Show humility in new interactions.",
"First Impressions Guide: A respectful presence goes far.",
"First Impressions Guide: Avoid comparisons with other countries.",
"First Impressions Guide: Speak respectfully about traditions.",
"First Impressions Guide: Ask open‑ended questions politely.",
"First Impressions Guide: Use simple and respectful language.",
"First Impressions Guide: Offer help when appropriate.",
"First Impressions Guide: Say goodbye with gratitude.",
"First Impressions Guide: Respectful tone always matters.",
"First Impressions Guide: Patience builds trust.",
"First Impressions Guide: A humble approach gains respect.",
"First Impressions Guide: Listening is as important as speaking.",
"First Impressions Guide: Ask before taking photos.",
"First Impressions Guide: Be polite and receptive.",
"First Impressions Guide: Honor local customs in words.",
"First Impressions Guide: Remain courteous regardless of setting.",
"First Impressions Guide: Greet every person you meet.",
"First Impressions Guide: Respect gender norms in greetings.",
"First Impressions Guide: Help create good memories.",
"First Impressions Guide: Enjoy cultural exchange openly.",
"First Impressions Guide: Respect starts with a hello.",

/* 2. History & Landmarks — 125 facts */
"History & Landmarks: Guatemala City was founded in 1776 after an earthquake leveled the old capital.",
"History & Landmarks: Antigua Guatemala is a UNESCO World Heritage Site.",
"History & Landmarks: Tikal is one of the largest archaeological sites of the ancient Maya.",
"History & Landmarks: The National Palace of Culture in Guatemala City was completed in 1943.",
"History & Landmarks: Quiriguá contains some of the tallest Mayan stelae ever discovered.",
"History & Landmarks: Lake Atitlán was formed by a massive volcanic eruption over 84,000 years ago.",
"History & Landmarks: The Miraflores Museum houses Mayan artifacts near Guatemala City.",
"History & Landmarks: The Catedral de Santiago in Antigua dates back to the 16th century.",
"History & Landmarks: Iximché was once the capital of the Kaqchikel Maya kingdom.",
"History & Landmarks: The Pacaya Volcano is one of Guatemala’s most active volcanoes.",
"History & Landmarks: The ruins of Zaculeu were a Mam Maya stronghold.",
"History & Landmarks: The Castillo de San Felipe de Lara guarded the Motagua River.",
"History & Landmarks: El Baúl and Bilbao are ancient Maya sites in the Pacific region.",
"History & Landmarks: The Church of La Merced in Antigua has an iconic Baroque facade.",
"History & Landmarks: Kaminaljuyú was an important pre‑classic Maya city in Guatemala City.",
"History & Landmarks: The Ixil Triangle is known for its historical significance during the civil war.",
"History & Landmarks: Mixco Viejo has ruins of a Postclassic Maya capital.",
"History & Landmarks: The National Museum of Archaeology and Ethnology showcases Guatemala’s cultures.",
"History & Landmarks: The San Juan Comalapa murals depict local life and history.",
"History & Landmarks: Guatemala has over 30 volcanoes across the country.",
"History & Landmarks: The Piedra del Toro at Iximché is a famous ceremonial stone.",
"History & Landmarks: The Palacio Nacional features murals of historical events.",
"History & Landmarks: Volcán Tajumulco is the highest point in Central America.",
"History & Landmarks: The Iglesia de Santo Domingo in Chichicastenango is central to local worship.",
"History & Landmarks: The Motagua Valley is rich in jade artifacts.",
"History & Landmarks: The El Zotz site has many impressive stelae and structures.",
"History & Landmarks: The Museo Popol Vuh has rare Mayan manuscripts.",
"History & Landmarks: The Plaza Mayor in Antigua hosts many festivals.",
"History & Landmarks: Huehuetenango has ruins reflecting ancient trade routes.",
"History & Landmarks: The Church of San Francisco in Antigua is a historic landmark.",
"History & Landmarks: The Museo Ixchel del Traje Indígena displays traditional textiles.",
"History & Landmarks: Petén is home to the majority of Guatemala’s Maya sites.",
"History & Landmarks: The Candelaria Caves have archaeological importance.",
"History & Landmarks: Uaxactún is one of the earliest Maya ceremonial centers.",
"History & Landmarks: Yaxhá overlooks a large natural lake.",
"History & Landmarks: Ceibal has ancient Maya architecture.",
"History & Landmarks: The ruins of Takalik Abaj date back over 2,000 years.",
"History & Landmarks: The Mayan city of Copán influenced early Guatemala.",
"History & Landmarks: Guatemala has colonial-era churches scattered across towns.",
"History & Landmarks: The Finca Filadelfia Coffee Plantation preserves history and nature.",
"History & Landmarks: El Mirador is an enormous Preclassic Maya site.",
"History & Landmarks: Zaculeu has restored pyramids that tourists can explore.",
"History & Landmarks: The Rio Dulce area has historic Spanish forts.",
"History & Landmarks: Antigua’s Santa Catalina Arch is a famous landmark.",
"History & Landmarks: The National Theatre in Guatemala City hosts cultural events.",
"History & Landmarks: The volcanoes of Guatemala shaped many towns.",
"History & Landmarks: Cobán is known for historical coffee plantations.",
"History & Landmarks: The old Guatemala City layout reflects colonial planning.",
"History & Landmarks: San Andrés and its ball court show Maya recreational life.",
"History & Landmarks: Chichicastenango hosts one of the largest indigenous markets.",
"History & Landmarks: The Iglesia de San José in Antigua has historic significance.",
"History & Landmarks: Guatemala has preserved several Mayan observatories.",
"History & Landmarks: The Museum of Modern Art houses historic artifacts.",
"History & Landmarks: The city of Livingston blends Garifuna and Mayan culture.",
"History & Landmarks: The Panajachel waterfront shows both history and beauty.",
"History & Landmarks: Antigua was once the colonial capital of Central America.",
"History & Landmarks: The town of Sololá offers views of Lake Atitlán and volcanoes.",
"History & Landmarks: Guatemala’s forts were used to protect trade routes.",
"History & Landmarks: The Choco Museum in Antigua explains historical chocolate production.",
"History & Landmarks: The ruins of Ixtutz reveal ancient Mayan religious practices.",
"History & Landmarks: The archaeological site of El Ceibal was occupied for over a millennium.",
"History & Landmarks: Guatemala has many historic bridges from the colonial period.",
"History & Landmarks: The Palacio de los Capitanes in Antigua is a notable landmark.",
"History & Landmarks: The ruins of La Blanca show complex urban planning in Maya times.",
"History & Landmarks: Guatemala City’s old cathedral was rebuilt several times after earthquakes.",
"History & Landmarks: The Piedra del Sol in Guatemala displays Mayan astronomical knowledge.",
"History & Landmarks: The town of Chimaltenango has ancient pottery traditions.",
"History & Landmarks: The town of Santiago Atitlán has preserved indigenous crafts.",
"History & Landmarks: Guatemala’s forts and watchtowers guarded colonial trade.",
"History & Landmarks: The Museo del Ferrocarril shows historic rail transport.",
"History & Landmarks: The Volcán de Fuego is one of the most photographed landmarks.",
"History & Landmarks: The ruins of Kaminaljuyú were once a major trade hub.",
"History & Landmarks: The town of Quetzaltenango is rich in cultural history.",
"History & Landmarks: The Museo Nacional de Historia displays historic maps.",
"History & Landmarks: Guatemala City’s old marketplace shows colonial architecture.",
"History & Landmarks: Antigua’s convent ruins are a glimpse into colonial times.",
"History & Landmarks: The Chocón volcano has historical eruptions documented by locals.",
"History & Landmarks: Guatemala has preserved many historical murals in churches.",
"History & Landmarks: The town of Huehuetenango shows Mayan influences in architecture.",
"History & Landmarks: The Monterrico area has historic pirate legends.",
"History & Landmarks: The Iglesia de la Merced has intricate baroque designs.",
"History & Landmarks: The town of Panajachel was a trading point during colonial times.",
"History & Landmarks: Guatemala’s jade sites were central to Mayan rituals.",
"History & Landmarks: The ruins of Mixco Viejo were rediscovered in the 20th century.",
"History & Landmarks: The town of Cobán is surrounded by historical coffee estates.",
"History & Landmarks: Antigua’s central plaza is surrounded by historic buildings.",
"History & Landmarks: The Petén region contains dozens of unexplored ruins.",
"History & Landmarks: The Santa Catalina Arch is often photographed by tourists.",
"History & Landmarks: Guatemala City was rebuilt after multiple earthquakes.",
"History & Landmarks: The ruins of Iximché have ceremonial plazas and temples.",
"History & Landmarks: Lake Atitlán villages retain traditional architecture.",
"History & Landmarks: The Panajachel market reflects historical trade practices.",
"History & Landmarks: Guatemala has preserved colonial archives for historians.",
"History & Landmarks: The Iglesia de San Francisco in Antigua features colonial murals.",
"History & Landmarks: Takalik Abaj shows early Maya influence from Olmec culture.",
"History & Landmarks: Volcán de Agua dominates the skyline near Antigua.",
"History & Landmarks: The Palacio Nacional has murals depicting independence.",
"History & Landmarks: Guatemala City’s old bridges are engineering landmarks.",
"History & Landmarks: The historic streets of Antigua maintain cobblestone paths.",
"History & Landmarks: The town of Sololá maintains ancient weaving traditions.",
"History & Landmarks: The town of Livingston has historical Afro-Caribbean influences.",
"History & Landmarks: Quiriguá’s stelae depict kings and astronomical events.",
"History & Landmarks: Guatemala preserves ancient ceremonial plazas for research.",
"History & Landmarks: Antigua’s churches survived multiple earthquakes with partial restoration.",
"History & Landmarks: Guatemala’s volcanoes shaped trade and settlement patterns.",
"History & Landmarks: Lake Atitlán was considered sacred by the Maya.",
"History & Landmarks: The ruins of Ceibal reveal complex ceremonial layouts.",
"History & Landmarks: Guatemala’s historical sites attract thousands of tourists annually.",

/* 3. Culture & Daily Life — 125 facts */
"Culture & Daily Life: Guatemalans eat breakfast early, usually around 7 am.",
"Culture & Daily Life: Traditional clothing is still worn by many in rural areas.",
"Culture & Daily Life: Markets are central to community life.",
"Culture & Daily Life: Spanish is the main language, but 21 Mayan languages are spoken.",
"Culture & Daily Life: Family is highly valued in daily life.",
"Culture & Daily Life: Guatemalans often enjoy afternoon coffee breaks.",
"Culture & Daily Life: Social gatherings often include music and dance.",
"Culture & Daily Life: Children commonly help in family businesses.",
"Culture & Daily Life: Community festivals bring villages together.",
"Culture & Daily Life: Many people maintain subsistence gardens.",
"Culture & Daily Life: Daily routines are influenced by local weather patterns.",
"Culture & Daily Life: Artisans sell crafts in markets as part of daily life.",
"Culture & Daily Life: Religion often intertwines with daily customs.",
"Culture & Daily Life: Soccer is the most popular sport in Guatemala.",
"Culture & Daily Life: Weekends often involve family visits and markets.",
"Culture & Daily Life: Handicrafts are often passed down through generations.",
"Culture & Daily Life: Guatemalans value storytelling as part of culture.",
"Culture & Daily Life: Coffee cultivation shapes work schedules.",
"Culture & Daily Life: Traditional music is played during special events.",
"Culture & Daily Life: Guatemalans use public buses and tuk-tuks for transport.",
"Culture & Daily Life: Local dialects and accents vary widely by region.",
"Culture & Daily Life: Women often weave textiles at home.",
"Culture & Daily Life: Community celebrations often include traditional foods.",
"Culture & Daily Life: Children attend school in the mornings and help at home in afternoons.",
"Culture & Daily Life: Elderly family members are respected and often cared for at home.",
"Culture & Daily Life: Markets are a hub for both shopping and socializing.",
"Culture & Daily Life: Guatemalans often greet neighbors daily.",
"Culture & Daily Life: Festivals often feature colorful traditional attire.",
"Culture & Daily Life: Local music genres include marimba and folk songs.",
"Culture & Daily Life: Guatemalans often celebrate saints’ days with special rituals.",
"Culture & Daily Life: Homemade tortillas are a staple at most meals.",
"Culture & Daily Life: Guatemalans celebrate birthdays with
```
